name: VoteReward
version: 0.3.2
main: com.tregele.bukkit.votereward.VoteReward
authors: [Siaynoq]
commands:
    votereward:
        description: Simulates the vote reward.
        usage: /<command> [player]
        permission: votereward.command
        permission-message: You don't have permission to execute this command
    vrreload:
        description: Reloads the config for vote reward
        usage: /<command>
        permission: votereward.command
        permission-message: You don't have permission to execute this command
